[build]
  publish = "dist"
  command = "npm ci --force && npm run build"
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/data/**"]

[build.environment]
  NODE_VERSION = "20"

# Production branch settings
[context.production]
  command = "npm ci --force && npm run build"

# Development branch settings  
[context.development]
  command = "npm ci --force && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
