import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Loader2, Download, Upload, CheckCircle, XCircle, AlertCircle } from 'lucide-react';
import { importStudents } from '@/services/firebaseService';
import type { Class, Student } from '@/types';

interface BulkStudentImportProps {
  classData: Class | null;
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

interface ParsedStudent {
  firstName: string;
  lastName: string;
  isValid: boolean;
  error?: string;
}

export const BulkStudentImport: React.FC<BulkStudentImportProps> = ({
  classData,
  isOpen,
  onClose,
  onSuccess
}) => {
  const [csvData, setCsvData] = useState('');
  const [parsedStudents, setParsedStudents] = useState<ParsedStudent[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  const downloadTemplate = () => {
    if (!classData) return;
    
    const template = 'firstName,lastName\nJohn,Smith\nJane,Doe\nBob,Johnson';
    const blob = new Blob([template], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    
    // Create class-specific filename: students-template-{classLevel}-{classDay}-{classTime}
    const sanitizedLevel = classData.classLevel.replace(/[^a-zA-Z0-9]/g, '');
    const sanitizedDay = classData.classDay.replace(/[^a-zA-Z0-9]/g, '');
    const sanitizedTime = classData.classTime.replace(/[^a-zA-Z0-9]/g, '');
    
    a.download = `students-template-${sanitizedLevel}-${sanitizedDay}-${sanitizedTime}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const parseCSV = (data: string): ParsedStudent[] => {
    const lines = data.trim().split('\n');
    const students: ParsedStudent[] = [];
    
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      if (!line) continue;
      
      // Split by comma, tab, or multiple spaces
      const parts = line.split(/[,\t]+|\s{2,}/).map(part => part.trim());
      
      if (parts.length < 2) {
        students.push({
          firstName: '',
          lastName: '',
          isValid: false,
          error: 'Missing firstName or lastName'
        });
        continue;
      }
      
      const [firstName, lastName] = parts;
      
      if (!firstName || !lastName) {
        students.push({
          firstName: firstName || '',
          lastName: lastName || '',
          isValid: false,
          error: 'firstName and lastName are required'
        });
        continue;
      }
      
      students.push({
        firstName,
        lastName,
        isValid: true
      });
    }
    
    return students;
  };

  const handleCSVChange = (value: string) => {
    setCsvData(value);
    setError(null);
    setSuccess(null);
    
    if (value.trim()) {
      const parsed = parseCSV(value);
      setParsedStudents(parsed);
    } else {
      setParsedStudents([]);
    }
  };

  const handleImport = async () => {
    if (!classData || parsedStudents.length === 0) return;
    
    const validStudents = parsedStudents.filter(s => s.isValid);
    if (validStudents.length === 0) {
      setError('No valid students to import');
      return;
    }
    
    setIsProcessing(true);
    setError(null);
    setSuccess(null);
    
    try {
      const studentsToImport: Student[] = validStudents.map(student => ({
        id: '', // Will be generated by createDoc
        classId: classData.id,
        firstName: student.firstName,
        lastName: student.lastName,
        teacherEmail: classData.teacherEmail,
        createdAt: new Date(),
        updatedAt: new Date()
      }));
      
      await importStudents(studentsToImport);
      
      setSuccess(`Successfully imported ${validStudents.length} students`);
      setCsvData('');
      setParsedStudents([]);
      
      // Notify parent component
      onSuccess();
      
      // Close modal after a short delay
      setTimeout(() => {
        onClose();
      }, 2000);
      
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to import students');
    } finally {
      setIsProcessing(false);
    }
  };

  const validCount = parsedStudents.filter(s => s.isValid).length;
  const invalidCount = parsedStudents.filter(s => !s.isValid).length;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Upload className="h-5 w-5" />
            Import Students for {classData?.classLevel} - {classData?.classDay} at {classData?.classTime}
          </DialogTitle>
        </DialogHeader>
        
        <div className="space-y-4">
          {/* Template Download */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm flex items-center gap-2">
                <Download className="h-4 w-4" />
                CSV Template
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-0">
              <p className="text-sm text-muted-foreground mb-3">
                Download the CSV template with the correct format for this specific class, then paste your student data below.
              </p>
              <Button variant="outline" size="sm" onClick={downloadTemplate}>
                <Download className="h-4 w-4 mr-2" />
                Download Template
              </Button>
            </CardContent>
          </Card>

          {/* CSV Input */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Student Data</CardTitle>
            </CardHeader>
            <CardContent className="pt-0">
              <Textarea
                placeholder="Paste your CSV data here (firstName,lastName)..."
                value={csvData}
                onChange={(e) => handleCSVChange(e.target.value)}
                className="min-h-[120px] font-mono text-sm"
                disabled={isProcessing}
              />
              <p className="text-xs text-muted-foreground mt-2">
                Format: firstName,lastName or firstName lastName or firstName	lastName (one student per line)
              </p>
            </CardContent>
          </Card>

          {/* Preview */}
          {parsedStudents.length > 0 && (
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm flex items-center gap-2">
                  Preview ({validCount} valid, {invalidCount} invalid)
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-0">
                <div className="space-y-2 max-h-[300px] overflow-y-auto border rounded-md p-2">
                  {parsedStudents.map((student, index) => (
                    <div key={index} className="flex items-center gap-2 p-2 rounded border">
                      <div className="flex-1">
                        <span className="font-medium">{student.firstName} {student.lastName}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        {student.isValid ? (
                          <Badge variant="default" className="text-xs">
                            <CheckCircle className="h-3 w-3 mr-1" />
                            Valid
                          </Badge>
                        ) : (
                          <Badge variant="destructive" className="text-xs">
                            <XCircle className="h-3 w-3 mr-1" />
                            {student.error}
                          </Badge>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Error/Success Messages */}
          {error && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
          
          {success && (
            <Alert className="border-green-200 bg-green-50 dark:border-green-800 dark:bg-green-950">
              <CheckCircle className="h-4 w-4 text-green-600" />
              <AlertDescription className="text-green-800 dark:text-green-200">
                {success}
              </AlertDescription>
            </Alert>
          )}

          {/* Actions */}
          <DialogFooter>
            <Button variant="outline" onClick={onClose} disabled={isProcessing}>
              Cancel
            </Button>
            <Button 
              onClick={handleImport} 
              disabled={isProcessing || validCount === 0}
            >
              {isProcessing ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Importing...
                </>
              ) : (
                <>
                  <Upload className="h-4 w-4 mr-2" />
                  Import {validCount} Students
                </>
              )}
            </Button>
          </DialogFooter>
        </div>
      </DialogContent>
    </Dialog>
  );
};
