import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Loader2, Upload, CheckCircle, XCircle, AlertCircle, Users } from 'lucide-react';
import { importStudents, getStudentsForClass } from '@/services/firebaseService-ultra-final';
import type { Class, Student } from '@/types';
import { parseStudentsCSV, type ParsedStudent } from '@/utils/studentCsv';

interface BulkStudentImportProps {
  classData: Class | null;
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

 

export function BulkStudentImport({
  classData,
  isOpen,
  onClose,
  onSuccess
}: BulkStudentImportProps) {
  const [csvData, setCsvData] = useState('');
  const [parsedStudents, setParsedStudents] = useState<ParsedStudent[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [existingStudents, setExistingStudents] = useState<Student[]>([]);
  const [loadingExisting, setLoadingExisting] = useState(false);

  // Load existing students when modal opens
  useEffect(() => {
    if (isOpen && classData) {
      loadExistingStudents();
    }
  }, [isOpen, classData]);

  const loadExistingStudents = async () => {
    if (!classData) return;
    
    setLoadingExisting(true);
    try {
      const students = await getStudentsForClass(classData.id);
      setExistingStudents(students);
    } catch (error) {
      console.error('Error loading existing students:', error);
    } finally {
      setLoadingExisting(false);
    }
  };

  const parseCSV = (data: string): ParsedStudent[] => {
    const lines = data.trim().split('\n');
    const students: ParsedStudent[] = [];
    
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      if (!line) continue;
      
      let firstName = '';
      let lastName = '';
      
      // Check if line contains comma or tab (CSV format)
      if (line.includes(',') || line.includes('\t')) {
        // CSV format: "firstName,lastName" or "firstName	lastName"
        const parts = line.split(/[,\t]/).map(part => part.trim());
        if (parts.length >= 2) {
          firstName = parts[0];
          // Join remaining parts as lastName (handles "De Los Reyes")
          lastName = parts.slice(1).join(' ');
        }
      } else {
        // Space-separated format: "firstName lastName" or "firstName middle lastName"
        // Handle nicknames in parentheses: "Jackie (Chen Wu) Li"
        const parts = line.split(/\s+/);
        
        if (parts.length >= 2) {
          // Check if there are parentheses (nickname)
          const hasParentheses = line.includes('(') && line.includes(')');
          
          if (hasParentheses) {
            // Extract everything up to and including the closing parenthesis as firstName
            const match = line.match(/^(.+\))\s+(.+)$/);
            if (match) {
              firstName = match[1].trim();
              lastName = match[2].trim();
            } else {
              // Fallback: first part is firstName, rest is lastName
              firstName = parts[0];
              lastName = parts.slice(1).join(' ');
            }
          } else {
            // No parentheses: first word is firstName, rest is lastName
            firstName = parts[0];
            lastName = parts.slice(1).join(' ');
          }
        }
      }
      
      // Validate
      if (!firstName || !lastName) {
        students.push({
          firstName: firstName || '',
          lastName: lastName || '',
          isValid: false,
          error: 'firstName and lastName are required'
        });
        continue;
      }
      
      students.push({
        firstName,
        lastName,
        isValid: true
      });
    }
    
    return students;
  };

  const handleCSVChange = (value: string) => {
    setCsvData(value);
    setError(null);
    setSuccess(null);
    
    if (value.trim()) {
      const parsed = parseCSV(value);
      setParsedStudents(parsed);
    } else {
      setParsedStudents([]);
    }
  };

  const handleImport = async () => {
    if (!classData || parsedStudents.length === 0) return;
    
    const validStudents = parsedStudents.filter(s => s.isValid);
    if (validStudents.length === 0) {
      setError('No valid students to import');
      return;
    }
    
    setIsProcessing(true);
    setError(null);
    setSuccess(null);
    
    try {
      const studentsToImport: Student[] = validStudents.map(student => ({
        id: '', // Will be generated by createDoc
        classId: classData.id,
        firstName: student.firstName,
        lastName: student.lastName,
        teacherEmail: classData.teacherEmail,
        createdAt: new Date(),
        updatedAt: new Date()
      }));
      
      await importStudents(studentsToImport);
      
      setSuccess(`Successfully imported ${validStudents.length} students`);
      setCsvData('');
      setParsedStudents([]);
      
      // Notify parent component
      onSuccess();
      
      // Close modal after a short delay
      setTimeout(() => {
        onClose();
      }, 2000);
      
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to import students');
    } finally {
      setIsProcessing(false);
    }
  };

  const validCount = parsedStudents.filter(s => s.isValid).length;
  const invalidCount = parsedStudents.filter(s => !s.isValid).length;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-[95vw] sm:max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Upload className="h-5 w-5" />
            Import Students for {classData?.classLevel} - {classData?.classDay} at {classData?.classTime}
          </DialogTitle>
          <DialogDescription>
            Import multiple students at once. Supports multi-word last names (De Los Reyes) and nicknames in parentheses (Jackie (Chen Wu) Li).
          </DialogDescription>
        </DialogHeader>
        
        <div className="space-y-4">
          {/* Existing Students */}
          <Card>
            <CardHeader className="pb-3">
              <h3 className="text-base font-semibold flex items-center gap-2">
                <Users className="h-4 w-4" />
                Existing Students in This Class
                <Badge variant="secondary" className="ml-2">{existingStudents.length}</Badge>
              </h3>
            </CardHeader>
            <CardContent className="pt-0">
              {loadingExisting ? (
                <div className="flex items-center justify-center p-4">
                  <Loader2 className="h-4 w-4 animate-spin mr-2" />
                  <span className="text-sm text-muted-foreground">Loading students...</span>
                </div>
              ) : existingStudents.length === 0 ? (
                <p className="text-sm text-muted-foreground">No students in this class yet.</p>
              ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 max-h-[200px] overflow-y-auto">
                  {existingStudents.map((student) => (
                    <div key={student.id} className="flex items-center gap-2 p-2 rounded border">
                      <div className="font-medium text-sm">
                        {student.firstName} {student.lastName}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>

          {/* CSV Input */}
          <Card>
            <CardHeader className="pb-3">
              <h3 className="text-base font-semibold">Student Data</h3>
            </CardHeader>
            <CardContent className="pt-0">
              <Textarea
                placeholder="Paste your CSV data here...&#10;Supports: firstName,lastName OR firstName lastName&#10;Multi-word last names: Ezra,De Los Reyes OR Ezra De Los Reyes&#10;Nicknames: Jackie (Chen Wu),Li OR Jackie (Chen Wu) Li&#10;Example:&#10;John,Smith&#10;Jane Doe&#10;Ezra De Los Reyes&#10;Jackie (Chen Wu) Li"
                value={csvData}
                onChange={(e) => handleCSVChange(e.target.value)}
                className="min-h-[120px] font-mono text-sm"
                disabled={isProcessing}
              />
            </CardContent>
          </Card>

          {/* Preview */}
          {parsedStudents.length > 0 && (
            <Card>
              <CardHeader className="pb-3">
                <h3 className="text-base font-semibold flex items-center gap-2">
                  Preview ({validCount} valid, {invalidCount} invalid)
                </h3>
              </CardHeader>
              <CardContent className="pt-0">
                <div className="space-y-2 max-h-[300px] overflow-y-auto border rounded-md p-2">
                  {parsedStudents.map((student, index) => (
                    <div key={index} className="flex items-center gap-2 p-2 rounded border">
                      <div className="flex-1">
                        <span className="font-medium">{student.firstName} {student.lastName}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        {student.isValid ? (
                          <Badge variant="default" className="text-xs">
                            <CheckCircle className="h-3 w-3 mr-1" />
                            Valid
                          </Badge>
                        ) : (
                          <Badge variant="destructive" className="text-xs">
                            <XCircle className="h-3 w-3 mr-1" />
                            {student.error}
                          </Badge>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Error/Success Messages */}
          {error && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
          
          {success && (
            <Alert className="border-green-200 bg-green-50 dark:border-green-800 dark:bg-green-950">
              <CheckCircle className="h-4 w-4 text-green-600" />
              <AlertDescription className="text-green-800 dark:text-green-200">
                {success}
              </AlertDescription>
            </Alert>
          )}

          {/* Actions */}
          <DialogFooter>
            <Button variant="outline" onClick={onClose} disabled={isProcessing}>
              Cancel
            </Button>
            <Button 
              onClick={handleImport} 
              disabled={isProcessing || validCount === 0}
            >
              {isProcessing ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Importing...
                </>
              ) : (
                <>
                  <Upload className="h-4 w-4 mr-2" />
                  Import {validCount} Students
                </>
              )}
            </Button>
          </DialogFooter>
        </div>
      </DialogContent>
    </Dialog>
  );
}
